# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alex Sonneveld
email: ~
description: > # this means to ignore newlines until "baseurl:"
  A personal blog and writings of an individual by the name of Alex Sonneveld,
  sometimes known as Sonna throughout the interwebs, a Ruby/Web developer and
  Video Games enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: AlexSonneveld
github_username:  Sonna

# Build settings
markdown: kramdown
theme: jekyll-theme-asonna # minima

# Structure configuration
# Where things are
source:       ./source
destination:  ./build
# layouts_dir:  ./_layouts
# data_dir:     ./_data
# includes_dir: ./_includes
# collections:  null
collections_dir: ./_collections
# plugins_dir:  ./_plugins
